---
- name: Set generic facts for ovftool
  ansible.builtin.set_fact:
    ovf_args: 
      - "{{ ovftool_bin }}"
      - --noSSLVerify=true

- name: Defining VM target
  ansible.builtin.set_fact:
    vm_target: "{{ 'vi://' + (vcenter_username | string | urlencode) + ':' + (vcenter_password | string | urlencode) + '@' + (vcenter_hostname | string) + '/' + (datacenter_name | string) + '/vm/' + (folder | string) + '/' + (name | string) }}"

- name: Adding ovftool target
  ansible.builtin.set_fact:
    command_to_execute: "{{ ovf_args + [ vm_target ] + [(name | string) + '.ovf'] }}"

- name: Debug info
  ansible.builtin.debug:
    msg: "Command to execute: {{ command_to_execute }}"

- name: Remove some files
  ansible.builtin.file:
    path: "{{ file }}"
    state: absent
  loop:
    - "{{ name }}-disk1.vmdk"
    - "{{ name }}-file1.nvram"
    - "{{ name }}.mf"
    - "{{ name }}.ovf"
    - "{{ name }}.ova"
  loop_control:
    loop_var: file
  delegate_to: localhost

- name: Run ovftool to export to ovf
  ansible.builtin.command:
    argv: "{{ command_to_execute }}"
  delegate_to: localhost

- name: Modify VirtualHardwareSection line in jumpcr.ovf
  ansible.builtin.lineinfile:
    path: jumpcr.ovf
    regexp: '^    <VirtualHardwareSection>'
    line: '    <VirtualHardwareSection ovf:transport="com.vmware.guestInfo">'
  delegate_to: localhost

- name: Remove file jumpcr.mf
  ansible.builtin.file:
    path: jumpcr.mf
    state: absent
  delegate_to: localhost

- name: Add ProductSection to jumpcr.ovf
  ansible.builtin.lineinfile:
    path: jumpcr.ovf
    regexp: '^  </VirtualSystem>'
    line: >-
        <ProductSection>
          <Info>Information about the installed software</Info>
          <Product>Cyber Recovery Automation - 2.0.0</Product>
          <Vendor>Vicente Martin</Vendor>
          <ProductUrl>https://github.com/DellAutomation/cyber-recovery-accelerator</ProductUrl>
          <Category>Networking</Category>
          <Property ovf:key="guestinfo.hostname" ovf:type="string" ovf:userConfigurable="true">
            <Label>Hostname</Label>
          </Property>
          <Property ovf:key="guestinfo.ipaddress" ovf:type="string" ovf:userConfigurable="true">
            <Label>IP Address</Label>
          </Property>
          <Property ovf:key="guestinfo.netmask" ovf:type="string" ovf:userConfigurable="true">
            <Label>Netmask</Label>
            <Description>(CIDR Format)</Description>
          </Property>
          <Property ovf:key="guestinfo.gateway" ovf:type="string" ovf:userConfigurable="true">
            <Label>Gateway</Label>
          </Property>
          <Property ovf:key="guestinfo.dns" ovf:type="string" ovf:userConfigurable="true">
            <Label>DNS Server</Label>
          </Property>
        </ProductSection>
        </VirtualSystem>
  delegate_to: localhost

- name: Adding ova target
  ansible.builtin.set_fact:
    command_to_execute: "{{ ovf_args + [(name | string) + '.ovf'] + [(name | string) + '.ova'] }}"

- name: Debug info
  ansible.builtin.debug:
    msg: "Command to execute: {{ command_to_execute }}"

- name: Run ovftool to convert to ova
  ansible.builtin.command:
    argv: "{{ command_to_execute }}"
  delegate_to: localhost

- name: Remove some files
  ansible.builtin.file:
    path: "{{ file }}"
    state: absent
  loop:
    - "{{ name }}-disk1.vmdk"
    - "{{ name }}-file1.nvram"
    - "{{ name }}.mf"
    - "{{ name }}.ovf"
  loop_control:
    loop_var: file
  delegate_to: localhost
