---
- name: Fetch secret
  no_log: true
  ansible.builtin.set_fact:
    secret: >-
      {{
        lookup(
          'kubernetes.core.k8s',
          api_version='v1',
          kind='Secret',
          namespace=namespace,
          resource_name=secret_name
        )
      }}

- name: Decode secret
  no_log: true
  ansible.builtin.set_fact:
    secret: "{{ secret['data'][secret_key_name] | b64decode }}"
  when: secret | length > 0