---
- name: Create mtree Uri 
  ansible.builtin.set_fact:
    dd_mtree_uri: "https://{{ dd_hostname }}:{{ dd_port }}{{ dd_resources.dd_systems }}/{{ dd_system_id }}/mtrees"

- name: Create mtree
  ansible.builtin.uri:
    validate_certs: "{{ dd_validate_certs }}"
    force_basic_auth: true
    url: "{{ dd_mtree_uri }}"
    method: POST
    status_code: [201]
    headers:
      Content-Type: application/json
      Accept: application/json
      X-DD-AUTH-TOKEN: "{{ x_dd_auth_token }}"
    body:
      mtree_create:
        name: "{{ create_mtree__name }}"
    body_format: json
  register: dd_createmtree_response
  retries: "{{ dd_uri_retries }}"
  delay: "{{ dd_uri_delay }}"
  until: dd_createmtree_response.status == 201
