---
- name: Enable ddboost Uri 
  ansible.builtin.set_fact:
    dd_ddboost_uri: "https://{{ dd_hostname }}:{{ dd_port }}{{ dd_resources.dd_systems }}/{{ dd_system_id }}/protocols/ddboost"

- name: Enable ddboost
  ansible.builtin.uri:
    validate_certs: "{{ dd_validate_certs }}"
    force_basic_auth: true
    url: "{{ dd_ddboost_uri }}"
    method: PUT
    status_code: [200]
    headers:
      Content-Type: application/json
      Accept: application/json
      X-DD-AUTH-TOKEN: "{{ x_dd_auth_token }}"
    body:
      ddboost_modify:
        operation: enable
    body_format: json
  register: dd_getddboostenable_response
  retries: "{{ dd_uri_retries }}"
  delay: "{{ dd_uri_delay }}"
  until: dd_getddboostenable_response.status == 200
