---
- name: Create user Uri 
  ansible.builtin.set_fact:
    dd_ddboost_uri: "https://{{ dd_hostname }}:{{ dd_port }}{{ dd_resources.dd_systems }}/{{ dd_system_id }}/protocols/ddboost"

- name: Get ddboost info
  ansible.builtin.uri:
    validate_certs: "{{ dd_validate_certs }}"
    force_basic_auth: true
    url: "{{ dd_ddboost_uri }}"
    method: GET
    headers:
      Content-Type: application/json
      Accept: application/json
      X-DD-AUTH-TOKEN: "{{ x_dd_auth_token }}"
  register: dd_getddboost_response
  retries: "{{ dd_uri_retries }}"
  delay: "{{ dd_uri_delay }}"
  until: dd_getddboost_response.status == 200
