---
- name: Preparation for metallb
  ansible.builtin.shell: >-
    kubectl get configmap kube-proxy -n kube-system -o yaml | \
    sed -e "s/strictARP: false/strictARP: true/" | \
    kubectl apply -f - -n kube-system

- name: Install metallb from manifest
  ansible.builtin.shell: >-
    kubectl apply -f {{ metallb_manifest }}

# TODO: this accessing the k8s and check for all pods be ready in the namespace
- name: Wait for pods to be ready
  ansible.builtin.pause:
    seconds: 120

- name: Create IPAddressPool
  kubernetes.core.k8s:
    state: present
    name: "{{ metallb_ipaddresspool_name }}"
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: "{{ metallb_ipaddresspool_name }}"
        namespace: "{{ metallb_namespace }}"
      spec:
        addresses: "{{ metallb_adresses }}"

- name: Create L2Advertisement
  kubernetes.core.k8s:
    state: present
    name: "{{ metallb_l2advertisement_name }}"
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: "{{ metallb_l2advertisement_name }}"
        namespace: "{{ metallb_namespace }}"
      spec:
        ipAddressPools: 
          - "{{ metallb_ipaddresspool_name }}"
