---
- name: Credential Uri 
  ansible.builtin.set_fact:
    ppdm_credentials_uri: "https://{{ ppdm_hostname }}:{{ ppdm_port }}{{ ppdm_resources.credentials }}"

- name: Create PPDM Data Domain Credential
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ ppdm_credentials_uri }}"
    method: POST
    headers:
      Content-Type: application/json
      Accept: application/json
      Authorization: "Bearer {{ ppdm_auth_token }}"
    return_content: true
    body:
      type: DATADOMAIN 
      name: "{{ cred_name }}"
      username: "{{ dd_username }}"
      password: "{{ dd_password }}"
    body_format: json
    status_code: 201
  register: ppdm_cred_result

- name: Set outputs
  ansible.builtin.set_fact:
    credential_id: "{{ ppdm_cred_result.json.id }}"
