---
- name: Credential Uri 
  ansible.builtin.set_fact:
    ppdm_credentials_uri: "https://{{ ppdm_hostname }}:{{ ppdm_port }}{{ ppdm_resources.credentials }}"

- name: Get Credentials
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ ppdm_credentials_uri }}"
    method: GET
    headers:
      Accept: application/json
      Authorization: "Bearer {{ ppdm_auth_token }}"
    return_content: true
    status_code: 200
  register: ppdm_cred_result

- name: Set outputs
  ansible.builtin.set_fact:
    ppdm_credential: "{{ ppdm_cred_result.json.content | selectattr('name', 'equalto', cred_name) | first }}"
