#!/bin/bash
set -euo pipefail

SAMBA_FOLDER=/srv/samba/share
IMAGE=cr-automation:latest

function usage {
    echo "usage: $0 <type of project file> <project file> <command>"
    echo ""
    echo "  where type of project file is one of"
    echo ""
    echo "    eps  \"The project file refers to a yml file extracted from EPS and converted wirh EPS cli\""
    echo "    inv  \"The project file refers to an ansible inventory yml file\""
    echo ""
    echo "  where command is one of"
    echo ""
    echo "    - cr_deploy \"Deploys Cyber Recovery to an esxi/vcenter\""
    echo "    - cr_setup \"Initializes Cyber Recovery software with random passwords stored in keepass\""
    echo "    - cr_users \"Creates configured users in Cyber Recovery with random passwords stored in keepass\""
    echo "    - cr_storage \"Adds Data Domain vault to Cyber Recovery and enables Disaster Recovery in Cyber Recovery. Depends on dd_setup\""
    echo "    - dd_setup \"Creates users, mtrees and enables ddboost in Data Domain for Cyber Recovery integration\""
    echo "    - dd_officer \"Checks data domain officer user is created or adds a new one\""
    echo "    - checks \"Does a list of checks in the environment needed for the automation\""
    echo "    - check_deployment \"Check the full automation\""
    echo "    - full_automation \"Does a full automation configuring Cyber Recovery and Data Domain in the right order\""
}

if [ "$#" -ne 3 ]
then
    usage
    exit 1
fi

# Check if the variable has a value of "eps" or "inv"
if [[ "$1" != "eps" && "$1" != "inv" ]]; then
    usage
    exit 1
fi

if [ "$1" = "inv" ]; then
    argument="--inventory="
else
    argument="--eps="
fi

PROJECT_FILE="$2"
usecase="$3"


set -o nounset

case "${usecase}" in
    cr_deploy|cr_setup|cr_users|cr_storage|dd_setup|dd_officer|checks|full_automation|check_deployment)
        docker run -i -t -v "${SAMBA_FOLDER}":/cr \
         -e EPS_CR_DATASTORE="${EPS_CR_DATASTORE}" \
         -e EPS_CR_DISK_MODE="${EPS_CR_DISK_MODE}" \
         -e EPS_CR_DNS="${EPS_CR_DNS}" \
         -e EPS_CR_NTP="${EPS_CR_NTP}" \
         -e EPS_CR_VM_NAME="${EPS_CR_VM_NAME}" \
         -e EPS_CR_CLUSTER_NAME="${EPS_CR_CLUSTER_NAME}" \
         -e EPS_CR_DATACENTER_NAME="${EPS_CR_DATACENTER_NAME}" \
         -e EPS_CR_FOLDER_NAME="${EPS_CR_FOLDER_NAME}" \
         -e EPS_CR_DEPLOY_TO_ESXI="${EPS_CR_DEPLOY_TO_ESXI}" \
         -e VC_USERNAME="${VC_USERNAME}" \
         -e VC_PASSWORD="${VC_PASSWORD}" \
         -e SYSADMIN_USERNAME="${SYSADMIN_USERNAME}" \
         -e SYSADMIN_PASSWORD="${SYSADMIN_PASSWORD}" \
         --rm "${IMAGE}" "${usecase}".sh \
         --local_folder=/cr \
         "${argument}"/cr/"${PROJECT_FILE}"
        ;;
    *)
        usage
        exit 1
        ;;
esac
