---
- name: Add Hard Disk
  ansible.builtin.script: >-
    add_hard_disk.ps1
    -vc_server "{{ vc_server }}"
    -vc_username "{{ vc_username }}"
    -vc_password "{{ vc_password }}"
    -vm_name "{{ vm_name }}"
    -vm_hard_disk_capacity_gb "{{ vm_hard_disk_capacity_gb }}"
    -datastore "{{ datastore }}"
    -disk_persistence "{{ disk_persistence }}"
    -storage_format "{{ storage_format }}"
  args:
    executable: /usr/bin/pwsh
  environment:
    NO_COLOR: "True"
  delegate_to: localhost
