---
- name: DR backup Uri 
  ansible.builtin.set_fact:
    cr_backup_uri: "https://{{ cr_hostname }}:{{ cr_port }}{{ cr_resources.drbackup }}"

- name: Get DR backup
  uri:
    url: "{{ cr_backup_uri }}"
    method: GET
    return_content: yes
    headers:
      X-CR-AUTH-TOKEN: "{{ cr_access_token }}"
    status_code: [200]
    validate_certs: "{{ cr_validate_certs }}"
  register: cr_drbackup_response
  retries: "{{ cr_uri_retries }}"
  delay: "{{ cr_uri_delay }}"
  until: cr_drbackup_response.status == 200
