- name: Deploy Cyber Recovery OVA
  hosts: "{{ variable_hosts }}"
  connection: local
  gather_facts: false
  tasks:
    - name: Set fact for local folder
      ansible.builtin.set_fact:
        local_folder: "{{ lookup('env', 'LOCAL_FOLDER') or '/tmp' }}"

    - name: Check if the ova exists locally
      ansible.builtin.stat:
        path: "{{ local_folder }}/{{ ova.name }}"
      register: ova_response

    - name: Download the ova
      ansible.builtin.include_role:
        name: dell.daf.vcenter
        tasks_from: get_from_datastore
      vars:
        vc_server: "{{ vcenter_hostname }}"
        vc_username: "{{ vcenter_username }}"
        vc_password: "{{ vcenter_password }}"
        datastore: "{{ datastore_name }}"
        source_path: "ova/dell/cr/{{ ova.name }}"
        target_path: "{{ local_folder }}/{{ ova.name }}"
      when: not ova_response.stat.exists

    - name: Deploy ova
      ansible.builtin.include_role:
        name: dell.daf.ova
      vars:
        vm_name: "{{ name }}"
        vm_folder: "{{ folder }}"
