---
- name: Compile Image
  hosts: jumpcr
  gather_facts: false
  become: false
  tasks:
    - name: Set facts
      ansible.builtin.set_fact:
        user_set_up: daf
        automation_repo: cyber-recovery-accelerator

    - name: Clone repo
      ansible.builtin.git:
        repo: "{{ repo.url }}"
        dest: "/home/{{ user_set_up }}/{{ repo.path }}"
        version: "{{ repo.version }}"
      loop:
        - url: git@github.com:vmartinvega-pivotal/cyber-recovery-accelerator.git
          path: "{{ automation_repo }}"
          version: refactor_for_eps
      loop_control:
        loop_var: repo

    - name: TODO. Investigare why this wait for docker to become ready to connect is needed, otherwise the build fails with permission denied
      ansible.builtin.pause:
        minutes: 5

    - name: Build image
      ansible.builtin.shell: >-
        cd /home/{{ user_set_up }}/{{ automation_repo }} && ./build/utils/docker_compile.sh 

    - name: Remove directory
      ansible.builtin.file:
        path: "/home/{{ user_set_up }}/{{ automation_repo }}"
        state: absent
