---
- name: Compile Image
  hosts: jumpcr
  gather_facts: false
  become: false
  tasks:
    - name: Set facts
      ansible.builtin.set_fact:
        user_set_up: daf
        automation_repo: cyber-recovery-accelerator

    - name: Clone repo
      ansible.builtin.git:
        repo: "{{ repo.url }}"
        dest: "/home/{{ user_set_up }}/{{ repo.path }}"
        version: "{{ repo.version }}"
      loop:
        - url: git@github.com:vmartinvega-pivotal/cyber-recovery-accelerator.git
          path: "{{ automation_repo }}"
          version: "{{ jumpcr_branch_to_compile }}"
      loop_control:
        loop_var: repo

    - name: Add user daf to docker group
      ansible.builtin.command: >-
        usermod -aG docker daf
      become: true
      changed_when: true
      register: add_user_to_docker_group

    - name: Change permissions for docker.sock
      ansible.builtin.command: >-
        chown daf /var/run/docker.sock
      become: true
      changed_when: true
      register: add_user_to_docker_group

    - name: Build image
      ansible.builtin.shell: >-
        cd /home/{{ user_set_up }}/{{ automation_repo }} && ./build/utils/docker_compile.sh
      changed_when: true

    - name: Remove directory
      ansible.builtin.file:
        path: "/home/{{ user_set_up }}/{{ automation_repo }}"
        state: absent
