---
- name: Deploy Ova
  hosts: jumpcrtest
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Set fact for local folder
      ansible.builtin.set_fact:
        local_folder: "./"

    - name: Set ova to test
      ansible.builtin.set_fact:
        ova: "{{ ova | combine({'name': variable_ova_to_test}) }}"

    - name: Check if the ova exists locally
      ansible.builtin.stat:
        path: "{{ local_folder }}/{{ ova.name }}"
      register: ova_response

    - name: Deploy ova
      ansible.builtin.include_role:
        name: dell.daf.ova
      vars:
        vm_name: "{{ name }}"
        vm_folder: "{{ folder }}"

# - name: Run Automations
#   hosts: jumpcrtest
#   gather_facts: false
#   become: false
#   tasks:
#     - name: Deploy Cyber Recory from automation
#       ansible.builtin.command: "cr_automation inventory.yml cr_deploy"
