---
- name: Export to ova
  hosts: jumpcr
  gather_facts: false
  tasks:
    - name: Shutdown VM
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ datacenter_name }}"
        name: "{{ name }}"
        state_change_timeout: 200
        state: powered-off
      delegate_to: localhost


    - name: Export ova
      ansible.builtin.include_role:
        name: dell.daf.accelerator
        tasks_from: export_to_ova
      vars:
        version: "{{ jumpcr_version }}"

    - name: Delete VM
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ datacenter_name }}"
        name: "{{ name }}"
        state: absent
      delegate_to: localhost
